// src/pages/Transactions.tsx
// components
import Layout from '../components/Layout/Layout';
import History from '../components/History/History';
import Divider from '../components/Divider/Divider';

// Transactions page listing detailed transaction history grouped by date
const Transactions: React.FC = () => (
  <Layout>
    <Divider />

    <h1 className='title no-select'>Transactions</h1>

    <History detailed date='May 6' dateBalance='-€127.78' />

    <Divider />

    <History detailed date='May 5' dateBalance='-€970.23' />

    <Divider />
  </Layout>
);

export default Transactions;

// src/app/pages/transactions/transactions.component.ts
import { Component } from '@angular/core';
import { LayoutComponent } from '../../components/layout/layout.component';
import { HistoryComponent } from '../../components/history/history.component';
import { DividerComponent } from '../../components/divider/divider.component';

@Component({
  selector: 'app-transactions',
  standalone: true,
  imports: [LayoutComponent, HistoryComponent, DividerComponent],
  template: `
    <app-layout>
      <app-divider />

      <h1 class="title no-select">Transactions</h1>

      <app-history [detailed]="true" date="May 6" dateBalance="-&euro;127.78" />

      <app-divider />

      <app-history [detailed]="true" date="May 5" dateBalance="-&euro;970.23" />

      <app-divider />
    </app-layout>
  `,
})
export class TransactionsComponent {}
