// src/app/components/form/input.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-input',
  standalone: true,
  template: `
    <div class="input-wrapper">
      <input
        [id]="name"
        [name]="name"
        [type]="type"
        [value]="value"
        [tabIndex]="tabIndex"
        [required]="required"
        [placeholder]="placeholder"
        [autocomplete]="autoComplete ? 'on' : 'off'"
        (input)="onInputChange($event)"
        [class]="'input' + (error ? ' input-error' : '')"
      />
      @if (error) {
        <span class="input-error-message">{{ error }}</span>
      }
    </div>
  `,
})
export class InputComponent {
  @Input() name = '';
  @Input() type = 'text';
  @Input() value = '';
  @Input() tabIndex = 0;
  @Input() required = false;
  @Input() placeholder = '';
  @Input() autoComplete = false;
  @Input() error = '';
  @Output() valueChange = new EventEmitter<string>();

  onInputChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.valueChange.emit(target.value);
  }
}

// src/components/Form/Input.tsx
// interfaces
interface IProps {
  name: string;
  type: string;
  value?: string;
  tabIndex: number;
  required?: boolean;
  placeholder: string;
  autoComplete?: boolean;
  error?: string;
  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
}

// Renders a text input with optional validation error message
const Input: React.FC<IProps> = ({
  name,
  type,
  value,
  tabIndex,
  placeholder,
  required = false,
  autoComplete = false,
  error,
  onChange,
}) => (
  <div className='input-wrapper'>
    <input
      id={name}
      name={name}
      type={type}
      value={value}
      tabIndex={tabIndex}
      required={required}
      placeholder={placeholder}
      autoComplete={autoComplete ? 'on' : 'off'}
      onChange={onChange}
      className={`input${error ? ' input-error' : ''}`}
    />
    {error && <span className='input-error-message'>{error}</span>}
  </div>
);

export default Input;
