// src/components/Arrow/Arrow.tsx
// Renders a downward arrow icon used as a visual separator between source and destination accounts
const Arrow: React.FC = () => (
  <div className='transfer-icon no-select'>
    <div className='transfer-circle flex flex-v-center flex-h-center'>
      <span className='material-symbols-outlined'>arrow_downward</span>
    </div>
  </div>
);

export default Arrow;

// src/app/components/arrow/arrow.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-arrow',
  standalone: true,
  template: `
    <div class="transfer-icon no-select">
      <div class="transfer-circle flex flex-v-center flex-h-center">
        <span class="material-symbols-outlined">arrow_downward</span>
      </div>
    </div>
  `,
})
export class ArrowComponent {}
