// src/app/components/card/card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-card',
  standalone: true,
  template: `
    <div class="card no-select">
      <div class="card-inner">
        <div class="front">
          <div class="row">
            <svg fill="#ffffff" width="27px" height="39px" viewBox="0 3.71 26.959 38.787">
              <path d="M19.709 3.719c.266.043.5.187.656.406 4.125 5.207 6.594 11.781 6.594 18.938 0 7.156-2.469 13.73-6.594 18.937-.195.336-.57.531-.957.492a.9946.9946 0 0 1-.851-.66c-.129-.367-.035-.777.246-1.051 3.855-4.867 6.156-11.023 6.156-17.718 0-6.696-2.301-12.852-6.156-17.719-.262-.317-.301-.762-.102-1.121.204-.36.602-.559 1.008-.504z" />
              <path d="M13.74 7.563c.231.039.442.164.594.343 3.508 4.059 5.625 9.371 5.625 15.157 0 5.785-2.113 11.097-5.625 15.156-.363.422-1 .472-1.422.109-.422-.363-.472-1-.109-1.422 3.211-3.711 5.156-8.551 5.156-13.843 0-5.293-1.949-10.133-5.156-13.844-.27-.309-.324-.75-.141-1.114.188-.367.578-.582.985-.542h.093z" />
              <path d="M7.584 11.438c.227.031.438.144.594.312 2.953 2.863 4.781 6.875 4.781 11.313 0 4.433-1.828 8.449-4.781 11.312-.398.387-1.035.383-1.422-.016-.387-.398-.383-1.035.016-1.421 2.582-2.504 4.187-5.993 4.187-9.875 0-3.883-1.605-7.372-4.187-9.875-.321-.282-.426-.739-.266-1.133.164-.395.559-.641.984-.617h.094zM1.178 15.531c.121.02.238.063.344.125 2.633 1.414 4.437 4.215 4.437 7.407 0 3.195-1.797 5.996-4.437 7.406-.492.258-1.102.07-1.36-.422-.257-.492-.07-1.102.422-1.359 2.012-1.075 3.375-3.176 3.375-5.625 0-2.446-1.371-4.551-3.375-5.625-.441-.204-.676-.692-.551-1.165.122-.468.567-.785 1.051-.742h.094z" />
            </svg>
            <svg fill="#ffffff" width="80px" height="80px" viewBox="0 0 24.00 24.00">
              <g stroke="#cccccc" stroke-width="0.048"></g>
              <g>
                <path d="M16.539 9.186a4.155 4.155 0 0 0-1.451-.251c-1.6 0-2.73.806-2.738 1.963-.01.85.803 1.329 1.418 1.613.631.292.842.476.84.737-.004.397-.504.577-.969.577-.639 0-.988-.089-1.525-.312l-.199-.093-.227 1.332c.389.162 1.09.301 1.814.313 1.701 0 2.813-.801 2.826-2.032.014-.679-.426-1.192-1.352-1.616-.563-.275-.912-.459-.912-.738 0-.247.299-.511.924-.511a2.95 2.95 0 0 1 1.213.229l.15.067.227-1.287-.039.009zm4.152-.143h-1.25c-.389 0-.682.107-.852.493l-2.404 5.446h1.701l.34-.893 2.076.002c.049.209.199.891.199.891h1.5l-1.31-5.939zm-10.642-.05h1.621l-1.014 5.942H9.037l1.012-5.944v.002zm-4.115 3.275.168.825 1.584-4.05h1.717l-2.551 5.931H5.139l-1.4-5.022a.339.339 0 0 0-.149-.199 6.948 6.948 0 0 0-1.592-.589l.022-.125h2.609c.354.014.639.125.734.503l.57 2.729v-.003zm12.757.606.646-1.662c-.008.018.133-.343.215-.566l.111.513.375 1.714H18.69v.001h.001z" />
              </g>
            </svg>
          </div>
          <div class="row card-no">
            <p>{{ number }}</p>
          </div>
          <div class="row card-holder">
            <p>CARD HOLDER</p>
            <p>VALID UNTIL</p>
          </div>
          <div class="row name">
            <p>{{ cardHolder }}</p>
            <p>{{ validUntil }}</p>
          </div>
        </div>
        <div class="back">
          <div class="bar"></div>
          <div class="row card-cvv">
            <div class="signature-back"></div>
            <p>{{ cvcNumber }}</p>
          </div>
          <div class="row card-text">
            <p>
              This card is property of Bank. If found, please return to Bank or to the nearest bank
              with Visa logo.
            </p>
          </div>
          <div class="row signature">
            <p>CUSTOMER SIGNATURE</p>
            <svg fill="#ffffff" width="80px" height="80px" viewBox="0 0 24.00 24.00">
              <g stroke="#cccccc" stroke-width="0.048"></g>
              <g>
                <path d="M16.539 9.186a4.155 4.155 0 0 0-1.451-.251c-1.6 0-2.73.806-2.738 1.963-.01.85.803 1.329 1.418 1.613.631.292.842.476.84.737-.004.397-.504.577-.969.577-.639 0-.988-.089-1.525-.312l-.199-.093-.227 1.332c.389.162 1.09.301 1.814.313 1.701 0 2.813-.801 2.826-2.032.014-.679-.426-1.192-1.352-1.616-.563-.275-.912-.459-.912-.738 0-.247.299-.511.924-.511a2.95 2.95 0 0 1 1.213.229l.15.067.227-1.287-.039.009zm4.152-.143h-1.25c-.389 0-.682.107-.852.493l-2.404 5.446h1.701l.34-.893 2.076.002c.049.209.199.891.199.891h1.5l-1.31-5.939zm-10.642-.05h1.621l-1.014 5.942H9.037l1.012-5.944v.002zm-4.115 3.275.168.825 1.584-4.05h1.717l-2.551 5.931H5.139l-1.4-5.022a.339.339 0 0 0-.149-.199 6.948 6.948 0 0 0-1.592-.589l.022-.125h2.609c.354.014.639.125.734.503l.57 2.729v-.003zm12.757.606.646-1.662c-.008.018.133-.343.215-.566l.111.513.375 1.714H18.69v.001h.001z" />
              </g>
            </svg>
          </div>
        </div>
      </div>
    </div>

    <div class="card-balance flex flex-v-center flex-space-between">
      <div class="flex flex-col flex-h-center flex-1 center">
        <h3>Balance</h3>
        <span>&euro; 783.45</span>
      </div>
      <div class="flex flex-col flex-h-center flex-1 center">
        <h3>Limit</h3>
        <span>&euro; 1250.00</span>
      </div>
    </div>
  `,
})
export class CardComponent {
  @Input() number = '';
  @Input() cvcNumber = '';
  @Input() validUntil = '';
  @Input() cardHolder = '';
}

// src/components/Card/Card.tsx
// interfaces
interface IProps {
  number: string;
  cvcNumber: string;
  validUntil: string;
  cardHolder: string;
}

// Renders a 3D-flippable credit card showing the front and back faces
const Card: React.FC<IProps> = ({ number, cvcNumber, validUntil, cardHolder }) => (
  <>
    <div className='card no-select'>
      <div className='card-inner'>
        {/* Front face: contactless icon, Visa logo, card number, holder name, and expiry */}
        <div className='front'>
          <div className='row'>
            <svg fill='#ffffff' width='27px' height='39px' viewBox='0 3.71 26.959 38.787'>
              <path d='M19.709 3.719c.266.043.5.187.656.406 4.125 5.207 6.594 11.781 6.594 18.938 0 7.156-2.469 13.73-6.594 18.937-.195.336-.57.531-.957.492a.9946.9946 0 0 1-.851-.66c-.129-.367-.035-.777.246-1.051 3.855-4.867 6.156-11.023 6.156-17.718 0-6.696-2.301-12.852-6.156-17.719-.262-.317-.301-.762-.102-1.121.204-.36.602-.559 1.008-.504z' />
              <path d='M13.74 7.563c.231.039.442.164.594.343 3.508 4.059 5.625 9.371 5.625 15.157 0 5.785-2.113 11.097-5.625 15.156-.363.422-1 .472-1.422.109-.422-.363-.472-1-.109-1.422 3.211-3.711 5.156-8.551 5.156-13.843 0-5.293-1.949-10.133-5.156-13.844-.27-.309-.324-.75-.141-1.114.188-.367.578-.582.985-.542h.093z' />
              <path d='M7.584 11.438c.227.031.438.144.594.312 2.953 2.863 4.781 6.875 4.781 11.313 0 4.433-1.828 8.449-4.781 11.312-.398.387-1.035.383-1.422-.016-.387-.398-.383-1.035.016-1.421 2.582-2.504 4.187-5.993 4.187-9.875 0-3.883-1.605-7.372-4.187-9.875-.321-.282-.426-.739-.266-1.133.164-.395.559-.641.984-.617h.094zM1.178 15.531c.121.02.238.063.344.125 2.633 1.414 4.437 4.215 4.437 7.407 0 3.195-1.797 5.996-4.437 7.406-.492.258-1.102.07-1.36-.422-.257-.492-.07-1.102.422-1.359 2.012-1.075 3.375-3.176 3.375-5.625 0-2.446-1.371-4.551-3.375-5.625-.441-.204-.676-.692-.551-1.165.122-.468.567-.785 1.051-.742h.094z' />
            </svg>
            <svg fill='#ffffff' width='80px' height='80px' viewBox='0 0 24.00 24.00'>
              <g stroke='#cccccc' strokeWidth='0.048' />
              <g>
                <path d='M16.539 9.186a4.155 4.155 0 0 0-1.451-.251c-1.6 0-2.73.806-2.738 1.963-.01.85.803 1.329 1.418 1.613.631.292.842.476.84.737-.004.397-.504.577-.969.577-.639 0-.988-.089-1.525-.312l-.199-.093-.227 1.332c.389.162 1.09.301 1.814.313 1.701 0 2.813-.801 2.826-2.032.014-.679-.426-1.192-1.352-1.616-.563-.275-.912-.459-.912-.738 0-.247.299-.511.924-.511a2.95 2.95 0 0 1 1.213.229l.15.067.227-1.287-.039.009zm4.152-.143h-1.25c-.389 0-.682.107-.852.493l-2.404 5.446h1.701l.34-.893 2.076.002c.049.209.199.891.199.891h1.5l-1.31-5.939zm-10.642-.05h1.621l-1.014 5.942H9.037l1.012-5.944v.002zm-4.115 3.275.168.825 1.584-4.05h1.717l-2.551 5.931H5.139l-1.4-5.022a.339.339 0 0 0-.149-.199 6.948 6.948 0 0 0-1.592-.589l.022-.125h2.609c.354.014.639.125.734.503l.57 2.729v-.003zm12.757.606.646-1.662c-.008.018.133-.343.215-.566l.111.513.375 1.714H18.69v.001h.001z' />
              </g>
            </svg>
          </div>
          <div className='row card-no'>
            <p>{number}</p>
          </div>
          <div className='row card-holder'>
            <p>CARD HOLDER</p>
            <p>VALID UNTIL</p>
          </div>
          <div className='row name'>
            <p>{cardHolder}</p>
            <p>{validUntil}</p>
          </div>
        </div>
        {/* Back face: magnetic strip, CVC, disclaimer text, and signature area */}
        <div className='back'>
          <div className='bar' />
          <div className='row card-cvv'>
            <div className='signature-back' />
            <p>{cvcNumber}</p>
          </div>
          <div className='row card-text'>
            <p>
              This card is property of Bank. If found, please return to Bank or to the nearest bank
              with Visa logo.
            </p>
          </div>
          <div className='row signature'>
            <p>CUSTOMER SIGNATURE</p>
            <svg fill='#ffffff' width='80px' height='80px' viewBox='0 0 24.00 24.00'>
              <g stroke='#cccccc' strokeWidth='0.048' />
              <g>
                <path d='M16.539 9.186a4.155 4.155 0 0 0-1.451-.251c-1.6 0-2.73.806-2.738 1.963-.01.85.803 1.329 1.418 1.613.631.292.842.476.84.737-.004.397-.504.577-.969.577-.639 0-.988-.089-1.525-.312l-.199-.093-.227 1.332c.389.162 1.09.301 1.814.313 1.701 0 2.813-.801 2.826-2.032.014-.679-.426-1.192-1.352-1.616-.563-.275-.912-.459-.912-.738 0-.247.299-.511.924-.511a2.95 2.95 0 0 1 1.213.229l.15.067.227-1.287-.039.009zm4.152-.143h-1.25c-.389 0-.682.107-.852.493l-2.404 5.446h1.701l.34-.893 2.076.002c.049.209.199.891.199.891h1.5l-1.31-5.939zm-10.642-.05h1.621l-1.014 5.942H9.037l1.012-5.944v.002zm-4.115 3.275.168.825 1.584-4.05h1.717l-2.551 5.931H5.139l-1.4-5.022a.339.339 0 0 0-.149-.199 6.948 6.948 0 0 0-1.592-.589l.022-.125h2.609c.354.014.639.125.734.503l.57 2.729v-.003zm12.757.606.646-1.662c-.008.018.133-.343.215-.566l.111.513.375 1.714H18.69v.001h.001z' />
              </g>
            </svg>
          </div>
        </div>
      </div>
    </div>

    {/* Balance and limit summary displayed below the card */}
    <div className='card-balance flex flex-v-center flex-space-between'>
      <div className='flex flex-col flex-h-center flex-1 center'>
        <h3>Balance</h3>
        <span>€ 783.45</span>
      </div>
      <div className='flex flex-col flex-h-center flex-1 center'>
        <h3>Limit</h3>
        <span>€ 1250.00</span>
      </div>
    </div>
  </>
);

export default Card;
