// src/app/pages/add/add.component.ts
import { Component } from '@angular/core';
import { LayoutComponent } from '../../components/layout/layout.component';
import { DividerComponent } from '../../components/divider/divider.component';
import { SavedComponent } from '../../components/add/saved.component';
import { ArrowComponent } from '../../components/arrow/arrow.component';
import { DestinationComponent } from '../../components/add/destination.component';
import { ButtonComponent } from '../../components/form/button.component';

@Component({
  selector: 'app-add',
  standalone: true,
  imports: [
    LayoutComponent,
    DividerComponent,
    SavedComponent,
    ArrowComponent,
    DestinationComponent,
    ButtonComponent,
  ],
  template: `
    <app-layout>
      <app-divider />

      <h1 class="title no-select">Add money</h1>

      <app-saved />

      <app-arrow />

      <app-destination />

      <app-divider />

      <div class="add-buttons flex flex-space-between">
        <app-button type="submit" text="Add money securely" [tabIndex]="0" />
      </div>

      <app-divider />
    </app-layout>
  `,
})
export class AddComponent {}

// src/pages/Add.tsx
// components
import Saved from '../components/Add/Saved';
import Arrow from '../components/Arrow/Arrow';
import Button from '../components/Form/Button';
import Layout from '../components/Layout/Layout';
import Divider from '../components/Divider/Divider';
import Destination from '../components/Add/Destination';

// Add Money page showing the saved source card, destination account, and submit button
const Add: React.FC = () => (
  <Layout>
    <Divider />

    <h1 className='title no-select'>Add money</h1>

    <Saved />

    <Arrow />

    <Destination />

    <Divider />

    <div className='add-buttons flex flex-space-between'>
      <Button type='submit' text='Add money securely' tabIndex={0} />
    </div>

    <Divider />
  </Layout>
);

export default Add;
