// src/app/pages/send-money/send-money.component.ts
import { Component } from '@angular/core';
import { LayoutComponent } from '../../components/layout/layout.component';
import { DividerComponent } from '../../components/divider/divider.component';

@Component({
  selector: 'app-send-money',
  standalone: true,
  imports: [LayoutComponent, DividerComponent],
  template: `
    <app-layout>
      <app-divider />

      <h1 class="title no-select">Send Money</h1>

      <p class="information text-shadow">Select a recipient to send money to.</p>

      <app-divider />
    </app-layout>
  `,
})
export class SendMoneyComponent {}

// src/pages/SendMoney.tsx
// components
import Layout from '../components/Layout/Layout';
import Divider from '../components/Divider/Divider';

// Send Money page prompting the user to select a recipient
const SendMoney: React.FC = () => (
  <Layout>
    <Divider />

    <h1 className='title no-select'>Send Money</h1>

    <p className='information text-shadow'>Select a recipient to send money to.</p>

    <Divider />
  </Layout>
);

export default SendMoney;
