// src/components/Actions/Actions.tsx
import { Link } from 'react-router-dom';

const Actions: React.FC = () => (
  <div className='actions flex flex-v-center flex-h-center'>
    <div className='circle no-select flex flex-col flex-v-center flex-h-center'>
      <Link to='/add' className='flex flex-v-center flex-h-center'>
        <span className='material-symbols-outlined'>add</span>
      </Link>
      <span className='text-shadow'>Add money</span>
    </div>
    <div className='circle no-select flex flex-col flex-v-center flex-h-center'>
      <Link to='/send' className='flex flex-v-center flex-h-center'>
        <span className='material-symbols-outlined'>send</span>
      </Link>
      <span className='text-shadow'>Send</span>
    </div>
    <div className='circle no-select flex flex-col flex-v-center flex-h-center'>
      <Link to='/transactions' className='flex flex-v-center flex-h-center'>
        <span className='material-symbols-outlined'>page_info</span>
      </Link>
      <span className='text-shadow'>Details</span>
    </div>
    <div className='circle no-select flex flex-col flex-v-center flex-h-center'>
      <Link to='/profile' className='flex flex-v-center flex-h-center'>
        <span className='material-symbols-outlined'>more_horiz</span>
      </Link>
      <span className='text-shadow'>More</span>
    </div>
  </div>
);

export default Actions;

// src/app/components/actions/actions.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-actions',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="actions flex flex-v-center flex-h-center">
      <div class="circle no-select flex flex-col flex-v-center flex-h-center">
        <a routerLink="/add" class="flex flex-v-center flex-h-center">
          <span class="material-symbols-outlined">add</span>
        </a>
        <span class="text-shadow">Add money</span>
      </div>
      <div class="circle no-select flex flex-col flex-v-center flex-h-center">
        <a routerLink="/send" class="flex flex-v-center flex-h-center">
          <span class="material-symbols-outlined">send</span>
        </a>
        <span class="text-shadow">Send</span>
      </div>
      <div class="circle no-select flex flex-col flex-v-center flex-h-center">
        <a routerLink="/home" class="flex flex-v-center flex-h-center">
          <span class="material-symbols-outlined">page_info</span>
        </a>
        <span class="text-shadow">Details</span>
      </div>
      <div class="circle no-select flex flex-col flex-v-center flex-h-center">
        <button type="button" class="flex flex-v-center flex-h-center">
          <span class="material-symbols-outlined">more_horiz</span>
        </button>
        <span class="text-shadow">More</span>
      </div>
    </div>
  `,
})
export class ActionsComponent {}
