// src/app/components/send/amount-input.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ButtonComponent } from '../form/button.component';

@Component({
  selector: 'app-amount-input',
  standalone: true,
  imports: [FormsModule, ButtonComponent],
  template: `
    <form (ngSubmit)="handleSubmit()">
      <div class="flex flex-v-center flex-h-center" style="margin: 30px 0">
        <span style="font-size: 2.5em; font-weight: 500; color: #ffffff; margin-right: 10px">
          {{ currencySymbol }}
        </span>
        <input
          type="number"
          [(ngModel)]="amount"
          name="amount"
          placeholder="0.00"
          style="font-size: 2.5em; font-weight: 500; color: #ffffff; background: transparent; border: none; outline: none; width: 200px; text-align: center"
        />
      </div>

      <p class="information text-shadow" style="text-align: center">
        Available: {{ currencySymbol }}{{ formatAmount(maxAmount) }}
      </p>

      @if (error) {
        <p class="input-error-message">{{ error }}</p>
      }

      <div class="add-buttons flex flex-space-between">
        <app-button type="submit" text="Continue" [tabIndex]="0" [disabled]="!amount" />
      </div>
    </form>
  `,
})
export class AmountInputComponent {
  @Input() maxAmount = 1325.5;
  @Input() currency = 'EUR';
  @Input() currencySymbol = '\u20ac';
  @Output() amountContinue = new EventEmitter<number>();

  amount = '';
  error = '';

  formatAmount(value: number): string {
    return value.toLocaleString('en-US', { minimumFractionDigits: 2 });
  }

  handleSubmit(): void {
    const parsed = parseFloat(this.amount);

    if (isNaN(parsed) || parsed <= 0) {
      this.error = 'Please enter a valid amount greater than 0';
      return;
    }

    if (parsed > this.maxAmount) {
      this.error = `Amount exceeds available balance of ${this.currencySymbol}${this.formatAmount(this.maxAmount)}`;
      return;
    }

    this.error = '';
    this.amountContinue.emit(parsed);
  }
}

// src/components/Send/AmountInput.tsx
import { useState } from 'react';

import Button from '../Form/Button';

// interfaces
interface IProps {
  onContinue: (amount: number) => void;
  maxAmount?: number;
  currency?: string;
  currencySymbol?: string;
}

// Renders a currency amount input with balance validation for the Send Money flow
const AmountInput: React.FC<IProps> = ({
  onContinue,
  maxAmount = 1325.5,
  currency = 'EUR',
  currencySymbol = '\u20ac',
}) => {
  const [amount, setAmount] = useState<string>('');
  const [error, setError] = useState<string>('');

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
    setAmount(e.target.value);
    setError('');
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>): void => {
    e.preventDefault();

    const parsed = parseFloat(amount);

    if (isNaN(parsed) || parsed <= 0) {
      setError('Please enter a valid amount greater than 0');
      return;
    }

    if (parsed > maxAmount) {
      setError(
        `Amount exceeds available balance of ${currencySymbol}${maxAmount.toLocaleString('en-US', { minimumFractionDigits: 2 })}`
      );
      return;
    }

    onContinue(parsed);
  };

  return (
    <form onSubmit={handleSubmit}>
      <div className='flex flex-v-center flex-h-center' style={{ margin: '30px 0' }}>
        <span style={{ fontSize: '2.5em', fontWeight: 500, color: '#ffffff', marginRight: '10px' }}>
          {currencySymbol}
        </span>
        <input
          type='number'
          value={amount}
          onChange={handleChange}
          placeholder='0.00'
          style={{
            fontSize: '2.5em',
            fontWeight: 500,
            color: '#ffffff',
            background: 'transparent',
            border: 'none',
            outline: 'none',
            width: '200px',
            textAlign: 'center',
          }}
        />
      </div>

      <p className='information text-shadow' style={{ textAlign: 'center' }}>
        Available: {currencySymbol}
        {maxAmount.toLocaleString('en-US', { minimumFractionDigits: 2 })}
      </p>

      {error && <p className='input-error-message'>{error}</p>}

      <div className='add-buttons flex flex-space-between'>
        <Button type='submit' text='Continue' tabIndex={0} disabled={!amount} />
      </div>
    </form>
  );
};

export default AmountInput;
