// src/app/components/send/transfer-success.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { ButtonComponent } from '../form/button.component';

@Component({
  selector: 'app-transfer-success',
  standalone: true,
  imports: [ButtonComponent],
  template: `
    <div class="flex flex-col flex-v-center flex-h-center" style="padding: 40px 0">
      <span
        class="material-symbols-outlined"
        style="font-size: 4em; color: #4ed34e; margin-bottom: 20px"
      >
        check_circle
      </span>
      <h1 class="title no-select">Transfer Successful!</h1>
      <p class="text-shadow" style="font-size: 2em; font-weight: 500; margin: 10px 0">
        {{ currencySymbol }}{{ amount.toFixed(2) }}
      </p>
      <p class="information text-shadow" style="margin-bottom: 30px">
        sent to {{ recipientName }}
      </p>
      <div class="add-buttons flex flex-space-between">
        <app-button type="button" text="Done" [tabIndex]="0" (buttonClick)="done.emit()" />
      </div>
    </div>
  `,
})
export class TransferSuccessComponent {
  @Input() amount = 0;
  @Input() currencySymbol = '\u20ac';
  @Input() recipientName = '';
  @Output() done = new EventEmitter<void>();
}

// src/components/Send/TransferSuccess.tsx
import Button from '../Form/Button';

// interfaces
interface IProps {
  amount: number;
  currencySymbol?: string;
  recipientName: string;
  onDone: () => void;
}

// Displays a success confirmation with checkmark, transferred amount, and recipient name
const TransferSuccess: React.FC<IProps> = ({
  amount,
  currencySymbol = '\u20ac',
  recipientName,
  onDone,
}) => (
  <div className='flex flex-col flex-v-center flex-h-center' style={{ padding: '40px 0' }}>
    <span
      className='material-symbols-outlined'
      style={{ fontSize: '4em', color: '#4ed34e', marginBottom: '20px' }}
    >
      check_circle
    </span>
    <h1 className='title no-select'>Transfer Successful!</h1>
    <p className='text-shadow' style={{ fontSize: '2em', fontWeight: 500, margin: '10px 0' }}>
      {currencySymbol}
      {amount.toFixed(2)}
    </p>
    <p className='information text-shadow' style={{ marginBottom: '30px' }}>
      sent to {recipientName}
    </p>
    <div className='add-buttons flex flex-space-between'>
      <Button type='button' text='Done' tabIndex={0} onClick={onDone} />
    </div>
  </div>
);

export default TransferSuccess;
