// src/app/components/add/destination.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-destination',
  standalone: true,
  template: `
    <div class="accounts flex flex-v-center flex-space-between">
      <div class="account-balance flex flex-col">
        <div class="flex flex-v-center no-select pointer">
          <span>EURO</span>
          <span class="material-symbols-outlined">keyboard_arrow_down</span>
        </div>
        <span class="account-balance-bottom">Balance: &euro; 231.40</span>
      </div>
      <div class="account-money flex flex-col right">
        <div class="flex flex-v-center flex-end">
          <span>&euro;</span>
          <input
            tabindex="0"
            class="account-balance-input right"
            value="0"
            type="text"
            placeholder="0"
            autocomplete="off"
          />
        </div>
        <span class="account-balance-bottom">No fee</span>
      </div>
    </div>
  `,
})
export class DestinationComponent {}

// src/components/Add/Destination.tsx
// Displays the destination account with currency selector and amount input for adding money
const Destination: React.FC = () => (
  <div className='accounts flex flex-v-center flex-space-between'>
    {/* Currency selector showing the active currency and current balance */}
    <div className='account-balance flex flex-col'>
      <div className='flex flex-v-center no-select pointer'>
        <span>EURO</span>
        <span className='material-symbols-outlined'>keyboard_arrow_down</span>
      </div>
      <span className='account-balance-bottom'>Balance: € 231.40</span>
    </div>
    {/* Amount input field with fee information */}
    <div className='account-money flex flex-col right'>
      <div className='flex flex-v-center flex-end'>
        <span>€</span>
        <input
          tabIndex={0}
          className='account-balance-input right'
          value='0'
          type='text'
          placeholder='0'
          autoComplete='off'
          onChange={() => {}}
        />
      </div>
      <span className='account-balance-bottom'>No fee</span>
    </div>
  </div>
);

export default Destination;
