// src/components/Circle/Circle.tsx
// interfaces
interface IProps {
  icon: string;
  color: string;
}

// Renders a colored circle with a material icon, used in transaction history rows
const Circle: React.FC<IProps> = ({ icon, color }) => (
  <div className={`flex flex-v-center flex-h-center no-select circle-icon ${color}`}>
    <span className='material-symbols-outlined'>{icon}</span>
  </div>
);

export default Circle;

// src/app/components/circle/circle.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-circle',
  standalone: true,
  template: `
    <div [class]="'flex flex-v-center flex-h-center no-select circle-icon ' + color">
      <span class="material-symbols-outlined">{{ icon }}</span>
    </div>
  `,
})
export class CircleComponent {
  @Input() icon = '';
  @Input() color = '';
}
