// src/components/Form/Button.tsx
// interfaces
interface IProps {
  type: string;
  text: string;
  tabIndex: number;
  disabled?: boolean;
  onClick?: () => void;
}

const Button: React.FC<IProps> = ({ type, text, tabIndex, disabled = false, onClick }) => (
  <button
    tabIndex={tabIndex}
    type={type === 'submit' ? 'submit' : 'button'}
    className={`button ${disabled ? 'disabled' : 'active'}`}
    disabled={disabled}
    onClick={onClick}
  >
    {text}
  </button>
);

export default Button;

// src/app/components/form/button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-button',
  standalone: true,
  template: `
    <button
      [tabIndex]="tabIndex"
      [type]="type === 'submit' ? 'submit' : 'button'"
      [class]="'button ' + (disabled ? 'disabled' : 'active')"
      (click)="buttonClick.emit()"
    >
      {{ text }}
    </button>
  `,
})
export class ButtonComponent {
  @Input() type = 'button';
  @Input() text = '';
  @Input() tabIndex = 0;
  @Input() disabled = false;
  @Output() buttonClick = new EventEmitter<void>();
}
